### ISSUE TITLE
Drop nsec mtime precision

### ISSUE THREAD

**Issue by alexlarsson** [giuseppe/composefs#11]
Does it really make sense to have nanosecond mtime precision in something like composefs? If we drop it that saves some space.

**Comment by giuseppe** [comment]
in an earlier implementation I was not using it, but it was suggested to me privately by someone in the file systems team (forgot whom exactly) to make it more generic, even if it costs more space.

**Comment by alexlarsson** [comment]
Yeah, lets err on the side of better feature support than size.

**Comment by cgwalters** [comment]
Anyone generating reproducible images will *need* to canonicalize timestamps.  ostree canonicalizes everything to zero, but as of lately I realized it also works if one is mapping e.g. deb/rpm to a container image layer to canonicalize to the package's build time for example.  

So would it help to optimize for the case where many files have the same timestamp?  (And in general, in most container images, most files are owned by uid/gid 0.  ostree static deltas represent this by having a "metadata offset" into a single shared table.  If we take (mtime, uid, gid) as a single unit, I bet many images would fit into a u8 i.e. 256 unique entries.  Almost all of them would fit into a u16.

**Comment by alexlarsson** [comment]
composefs actually did separate some of the stat data to a separate part which was deduplicated. However, the savings weren't really that large and the costs in terms of complexity and sparsity of the data (and thus seekiness when reading) were large enough that i'm dropping that and mainly focusing on dedup for the xattrs, and putting everything else in single chunks for good cacheabitlity and minimal i/o ops.

**Comment by cgwalters** [comment]
A shared metadata table with (mtime, uid, gid) = 16 bytes, multiplied by 256 exactly equals 4096 bytes, a single page which surely we could just read once into memory.

Hm, we also have ctime, which again in reproducible cases will always equal mtime, so the "shared inode meta" would be 24 bytes.  

Most files also will have a link count of one, and a zero device ID, which could be canonicalized.

But yeah, needs some real analysis and probably should also look at whether squashfs and erofs do anything like this.

**Comment by alexlarsson** [comment]
I'd like to avoid the complexity that comes with implementing all the corner case of such smartness in the kernel too. Suddely you go past 256 shared metadata, and now the size of all your inodes changes and you need to use a different encoding for that and affect everything.

**Comment by cgwalters** [comment]
I think here it's more instead of having a basic `lcfs_off_t inode_index;` in `struct lcfs_dentry_s` we reuse some extra bits there to say whether or not to look up the inode metadata in the shared table or not.

I understand and agree with the perspective of Keeping It Simple, but...on the flip side, in my experience as soon as you have e.g. Python shipped as part of the OS or containers which wants to drop *lots* and *lots* of zero-sized `__init__.py` files all over the place, the metadata/data ratio can grow a lot.

(And sadly because we don't have a time machine to ship Rust earlier, there's still a lot of Python in at least our operating system stuff)

**Comment by alexlarsson** [comment]
I think what we could do is have a flag field at the start of the inode and make it variable size. Then at the cost of having to do two reads for the inode data (first to get the size) we can easily handle "unset" (default valued) parts. Which does *most* of what the shared metadata does really. I'm currently restructuring the inode tables, so will look at doing that.

**Comment by alexlarsson** [comment]
So, with the current head my testcase which is a 700mb CS9 ostree checkout create with --relative the resulting file is about 3M, and contains 22010 inodes.

If we assume those were all zero uid, gid, mtime and ctime, then we would save at most 40 bytes per inode (ignoring that we would need to add a flag and whatnot). This would save 440k in the 4M file. Not a *huge* gain for the best case.

**Comment by cgwalters** [comment]
Given that we intend to use this for other images too, I think we should include more than just that one build when gathering data. There's also e.g. Fedora Silverblue, or `docker.io/tensorflow/tensorflow` from Docker hub, or all the images which are part of an OCP release image, or some of the top popular images from Docker Hub, etc.

But on the other hand I don't have the bandwidth to really drive this sub-thread; if we ship a first release and it doesn't have optimizations here, that's likely going to be fine.  Probably more important to focus on the integrity aspects at least.

**Comment by alexlarsson** [comment]
Might be interesting to run the ostree-convert-commit.py on various more workloads so that we can use it as data for this.

Anyway, I've been thinking a bit about this and we have a 8-bit hole in the lcfs_dentry_s structure already, which we could easily turn into a flag. And that flag could be like "use default mtime values from filesystem header". The one problem with this is that we then *have* to use dentries to look up inodes, which means we can't implement cfs_fh_to_dentry() which is needed to look up inodes by inode nr for exporting the filesystem (via nfs). However, this is an optional feature which we could potentially drop. (Or alternatively duplicate the flag early in the inode and read it twice in fh_to_dentry.

**Comment by alexlarsson** [comment]
I see that st_nlink is now an uint32_t. That could easily be smaller and give us an 8bit flag.

**Comment by alexlarsson** [comment]
I'm doing some work on this now, but i'm using some bits from the 64bit inode nr for the flags instead, thus allowing export to still work (and 56 bits for offset in the inode table should be fine).
